apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/java-quarkus-098/base
- components/java-quarkus-sample/base
- components/java-springboot-sample/base
- components/python-sample/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
